package n_reinas;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author david
 */
public class GeneticoGUI extends javax.swing.JFrame {
    private GeneticoNReinas genetico;
    private DefaultListModel<String> log = new DefaultListModel<>();
    private ManagerGUI mg;
    /**
     * Creates new form GeneticoGUI
     */
    public GeneticoGUI() {
        initComponents();
    }
    
    public GeneticoGUI(GeneticoNReinas gen, ManagerGUI mg) {
        initComponents();
        this.setVisible(true);
        this.genetico = gen;
        this.mg = mg;
        // Ponemos sus valores
        this.hashCode.setText(String.valueOf(this.genetico.hashCode()));
        this.txtNumGeneraciones.setText(String.valueOf(
            this.genetico.getConfiguracion().getNumGeneraciones()));
        this.txtTamPoblacion.setText(String.valueOf(
            this.genetico.getConfiguracion().getTamPoblacion()));
        this.txtProbMuta.setText(String.valueOf(
            this.genetico.getConfiguracion().getProbMuta()));
        this.txtPorcentajeMuestra.setText(String.valueOf(
            this.genetico.getConfiguracion().getpMuestra()));
        String mask = Arrays.toString(this.genetico.getConfiguracion().getMascara());
        if(mask.length() > 20) {
            mask = mask.substring(0, 20) + "...";
        }
        this.lblMascara.setText(mask);
        this.cbxSeleccion.removeAllItems();
        Seleccion.TipoSeleccion tipoSelecion[] = 
            this.genetico.getConfiguracion().getTipoSelecion();
        if(tipoSelecion[0] == Seleccion.TipoSeleccion.TORNEO) {
            this.cbxSeleccion.addItem("Torneo");
            this.cbxSeleccion.setSelectedItem("Torneo");
            this.cbxSeleccion.addItem("Aleatorio");
        }
        else {
            this.cbxSeleccion.addItem("Aleatorio");
            this.cbxSeleccion.setSelectedItem("Aleatorio");
            this.cbxSeleccion.addItem("Torneo");
        }
        // Setear el checkbox de graficar al terminar
        if(this.genetico.isGraficarAlTerminar()) this.chbxHistoria.setSelected(true);
        else this.chbxHistoria.setSelected(false);
        // Configurar lista log
        this.listLog.setModel(this.log);
        // Setear las listas y modelo del log al genético 
        this.genetico.setListLog(this.listLog);
        this.genetico.setLog(this.log);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMascara = new javax.swing.JLabel();
        lblMascara1 = new javax.swing.JLabel();
        cbxSeleccion = new javax.swing.JComboBox<>();
        chbxHistoria = new javax.swing.JCheckBox();
        btnDetener = new javax.swing.JButton();
        txtNumGeneraciones = new javax.swing.JTextField();
        txtTamPoblacion = new javax.swing.JTextField();
        txtProbMuta = new javax.swing.JTextField();
        txtPorcentajeMuestra = new javax.swing.JTextField();
        btnMascara = new javax.swing.JButton();
        btnNumGeneraciones = new javax.swing.JButton();
        btnTamPoblacion = new javax.swing.JButton();
        btnProbMuta = new javax.swing.JButton();
        btnPorcentajeMuestra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLog = new javax.swing.JList<>();
        hashCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Núm. Generaciones:");

        jLabel2.setText("Tamaño población:");

        jLabel3.setText("Probabilidad muta:");

        jLabel4.setText("Porcentaje muestra:");

        jLabel5.setText("Máscara");

        lblMascara.setText("01010101...");

        lblMascara1.setText("Elegir modo de selección:");

        cbxSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSeleccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSeleccionItemStateChanged(evt);
            }
        });
        cbxSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionActionPerformed(evt);
            }
        });

        chbxHistoria.setText("Graficar historia al finalizar");
        chbxHistoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxHistoriaStateChanged(evt);
            }
        });

        btnDetener.setText("Detener");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });

        btnMascara.setText("Actualizar");
        btnMascara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascaraActionPerformed(evt);
            }
        });

        btnNumGeneraciones.setText("Actualizar");
        btnNumGeneraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumGeneracionesActionPerformed(evt);
            }
        });

        btnTamPoblacion.setText("Actualizar");
        btnTamPoblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamPoblacionActionPerformed(evt);
            }
        });

        btnProbMuta.setText("Actualizar");
        btnProbMuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbMutaActionPerformed(evt);
            }
        });

        btnPorcentajeMuestra.setText("Actualizar");

        listLog.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listLog);

        hashCode.setText("hashCode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumGeneraciones)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTamPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTamPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProbMuta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtPorcentajeMuestra))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProbMuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPorcentajeMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMascara)
                                    .addComponent(lblMascara1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxSeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hashCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chbxHistoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumGeneraciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTamPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTamPoblacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProbMuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProbMuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPorcentajeMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPorcentajeMuestra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnMascara)
                    .addComponent(hashCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMascara)
                        .addGap(39, 39, 39)
                        .addComponent(lblMascara1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(chbxHistoria)
                        .addGap(14, 14, 14)
                        .addComponent(btnDetener)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ## ACTUALIZAR LA PROBABILIDAD DE MUTA ##
    private void btnProbMutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbMutaActionPerformed
        double nuevaProbMuta = Double.parseDouble(this.txtProbMuta.getText());
        this.genetico.getConfiguracion().setProbMuta(nuevaProbMuta);
    }//GEN-LAST:event_btnProbMutaActionPerformed

    // ## ACTUALIZAR TAMAÑO DE LA POBLACIÓN ##
    private void btnTamPoblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamPoblacionActionPerformed
        int nuevoTamPob = Integer.parseInt(this.txtTamPoblacion.getText());
        this.genetico.getConfiguracion().setTamPoblacion(nuevoTamPob);
    }//GEN-LAST:event_btnTamPoblacionActionPerformed

    // ## ACTUALIZAR EL NÚMERO DE GENERACIONES ##
    private void btnNumGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumGeneracionesActionPerformed
        int nuevoNumGeneraciones = Integer.parseInt(this.txtNumGeneraciones.getText());
        this.genetico.getConfiguracion().setNumGeneraciones(nuevoNumGeneraciones);
    }//GEN-LAST:event_btnNumGeneracionesActionPerformed

    // ## ACTUALIZAR LA MÁSCARA DE CRUZA ##
    private void btnMascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascaraActionPerformed
        int n = this.genetico.getConfiguracion().getN();
        this.genetico.getConfiguracion().setMascara(Cruza.generarMascaraAleatoria(n));
        String mask = Arrays.toString(this.genetico.getConfiguracion().getMascara());
        if(mask.length() > 20) {
            mask = mask.substring(0, 20) + "...";
        }
        this.lblMascara.setText(mask);
    }//GEN-LAST:event_btnMascaraActionPerformed

    private void cbxSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionActionPerformed
        
    }//GEN-LAST:event_cbxSeleccionActionPerformed

    // ## DETENER EL HILO DEL GENÉTICO ##
    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        this.genetico.getHilo().stop();
        // deshabilitar el botón de detener
        this.btnDetener.setEnabled(false);
        // Y otros botones
        this.btnTamPoblacion.setEnabled(false);
        this.btnMascara.setEnabled(false);
        this.btnNumGeneraciones.setEnabled(false);
        this.btnPorcentajeMuestra.setEnabled(false);
        this.btnProbMuta.setEnabled(false);
        this.cbxSeleccion.setEnabled(false);
        
    }//GEN-LAST:event_btnDetenerActionPerformed

    // ## ACTUALIZAR EL TIPO DE SELECCIÓN ##
    private void cbxSeleccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSeleccionItemStateChanged
        String modoSeleccion = (String) this.cbxSeleccion.getSelectedItem();
        Seleccion.TipoSeleccion ts[];
        if(modoSeleccion != null) {
            if(modoSeleccion.equals("Aleatorio")) {
                ts = new Seleccion.TipoSeleccion[] {
                    Seleccion.TipoSeleccion.RANDOM,
                    Seleccion.TipoSeleccion.TORNEO
                };
            }
            else{
                ts = new Seleccion.TipoSeleccion[] {
                    Seleccion.TipoSeleccion.TORNEO,
                    Seleccion.TipoSeleccion.RANDOM
                }; 
            }
            // Seteamos en el genético el nuevo tipo de selección
            this.genetico.getConfiguracion().setTipoSelecion(ts);
        }
    }//GEN-LAST:event_cbxSeleccionItemStateChanged

    // ## ACTUALIZAR LA BANDERA PARA MOSTRAR LA GRÁFICA AL FINAL O NO
    private void chbxHistoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxHistoriaStateChanged
        if(this.chbxHistoria.isSelected()) this.genetico.setGraficarAlTerminar(true);
        else this.genetico.setGraficarAlTerminar(false);
    }//GEN-LAST:event_chbxHistoriaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneticoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneticoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneticoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneticoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneticoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnMascara;
    private javax.swing.JButton btnNumGeneraciones;
    private javax.swing.JButton btnPorcentajeMuestra;
    private javax.swing.JButton btnProbMuta;
    private javax.swing.JButton btnTamPoblacion;
    private javax.swing.JComboBox<String> cbxSeleccion;
    private javax.swing.JCheckBox chbxHistoria;
    private javax.swing.JLabel hashCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMascara;
    private javax.swing.JLabel lblMascara1;
    private javax.swing.JList<String> listLog;
    private javax.swing.JTextField txtNumGeneraciones;
    private javax.swing.JTextField txtPorcentajeMuestra;
    private javax.swing.JTextField txtProbMuta;
    private javax.swing.JTextField txtTamPoblacion;
    // End of variables declaration//GEN-END:variables
}
